# Generated by Django 3.2 on 2021-04-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict',
            name='label_predict',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predict',
            name='label_probability',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
    ]
